sudo: false

language: ruby

cache: bundler

services: mongodb

rvm:
  - 2.5.3

before_install:
  - gem update bundler

before_script:
  - bundle exec danger

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

env:
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6
  - MONGOID_VERSION=7
  - MONGOID_VERSION=HEAD

matrix:
  allow_failures:
    - env: MONGOID_VERSION=HEAD
